/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicArticlesRouteImport } from './routes/_public/articles'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users.index'
import { Route as AdminSubscribersIndexRouteImport } from './routes/admin/subscribers.index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings.index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts.index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages.index'
import { Route as AdminMessagesIndexRouteImport } from './routes/admin/messages.index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories.index'
import { Route as AdminPostsIdRouteImport } from './routes/admin/posts.$id'
import { Route as PublicPostSlugRouteImport } from './routes/_public/post.$slug'
import { Route as PublicCategorySlugRouteImport } from './routes/_public/category.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicArticlesRoute = PublicArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersIndexRoute = AdminSubscribersIndexRouteImport.update({
  id: '/subscribers/',
  path: '/subscribers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesIndexRoute = AdminMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const PublicPostSlugRoute = PublicPostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCategorySlugRoute = PublicCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/articles': typeof PublicArticlesRoute
  '/contact': typeof PublicContactRoute
  '/admin/': typeof AdminIndexRoute
  '/category/$slug': typeof PublicCategorySlugRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/messages/': typeof AdminMessagesIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/subscribers/': typeof AdminSubscribersIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/articles': typeof PublicArticlesRoute
  '/contact': typeof PublicContactRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/category/$slug': typeof PublicCategorySlugRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/messages': typeof AdminMessagesIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/subscribers': typeof AdminSubscribersIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/articles': typeof PublicArticlesRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/category/$slug': typeof PublicCategorySlugRoute
  '/_public/post/$slug': typeof PublicPostSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/messages/': typeof AdminMessagesIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/subscribers/': typeof AdminSubscribersIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/articles'
    | '/contact'
    | '/admin/'
    | '/category/$slug'
    | '/post/$slug'
    | '/admin/posts/$id'
    | '/admin/categories/'
    | '/admin/messages/'
    | '/admin/pages/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/subscribers/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/articles'
    | '/contact'
    | '/'
    | '/admin'
    | '/category/$slug'
    | '/post/$slug'
    | '/admin/posts/$id'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/users'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_public/about'
    | '/_public/articles'
    | '/_public/contact'
    | '/_public/'
    | '/admin/'
    | '/_public/category/$slug'
    | '/_public/post/$slug'
    | '/admin/posts/$id'
    | '/admin/categories/'
    | '/admin/messages/'
    | '/admin/pages/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/subscribers/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/articles': {
      id: '/_public/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof PublicArticlesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers/': {
      id: '/admin/subscribers/'
      path: '/subscribers'
      fullPath: '/admin/subscribers/'
      preLoaderRoute: typeof AdminSubscribersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages/': {
      id: '/admin/messages/'
      path: '/messages'
      fullPath: '/admin/messages/'
      preLoaderRoute: typeof AdminMessagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/post/$slug': {
      id: '/_public/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PublicPostSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/category/$slug': {
      id: '/_public/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof PublicCategorySlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicArticlesRoute: typeof PublicArticlesRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCategorySlugRoute: typeof PublicCategorySlugRoute
  PublicPostSlugRoute: typeof PublicPostSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicArticlesRoute: PublicArticlesRoute,
  PublicContactRoute: PublicContactRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCategorySlugRoute: PublicCategorySlugRoute,
  PublicPostSlugRoute: PublicPostSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminMessagesIndexRoute: typeof AdminMessagesIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminSubscribersIndexRoute: typeof AdminSubscribersIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminMessagesIndexRoute: AdminMessagesIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminSubscribersIndexRoute: AdminSubscribersIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
